[package]
name = "gitcli"
version = "0.1.0"
authors = ["Esraa Jbara <jbesraa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
thiserror = "1.0.20"
crossterm = "0.17.7"
chrono = "0.4.15"